name: Deploy to EC2

# Trigger deployment only on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Clear and Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Clear target directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            rm -rf ${{ secrets.TARGET_DIR }}/*

      - name: Deploy files to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          SOURCE: "."
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Install Dependencies and Start Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Load NVM
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            
            # Navigate to the backend directory
            cd /home/ubuntu/home/backend

            # Install dependencies
            npm install

            # Use PM2 to start your application
            # First, stop any existing process
            npm install -g pm2
            pm2 delete backend-app || true  # Ignore error if the process doesn't exist

            # Start the application with PM2
            pm2 start server.js --name backend-app
