name: Deploy to EC2

# Trigger deployment only on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Clear and Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Clear target directory and Deploy files to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          ARGS: "rm -rf ${{ secrets.TARGET_DIR }}/*"
          SOURCE: "."
          TARGET: ${{ secrets.TARGET_DIR }}
